/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package clean.code.cast

import io.ktor.application.*
import io.ktor.http.*
import io.ktor.response.*
import io.ktor.routing.*
import io.ktor.server.netty.Netty
import io.ktor.server.engine.embeddedServer


fun main() {
    embeddedServer(Netty, 8081) {
        routing {
            get("/") {
                println("home access")
                call.respondText("Hello from ktor")
            }
        }
    }.start(wait = true)
}
